# Generated by Django 4.2.2 on 2023-06-18 18:42

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Workout_Logbook', '0002_prefilledexercise_customuserexercise_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserexercise',
            name='equipment',
            field=models.CharField(choices=[('bod', 'body only'), ('mac', 'machine'), ('ket', 'kettlebells'), ('dum', 'dumbbell'), ('cab', 'cable'), ('bar', 'barbell'), ('ban', 'bands'), ('med', 'medicine ball'), ('exe', 'exercise ball'), ('cba', 'e-z curl bar'), ('fro', 'foam roll')], default='mac', max_length=3, null=True, verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='customuserexercise',
            name='force',
            field=models.CharField(choices=[('pull', 'Pull'), ('push', 'Push'), ('stat', 'Static')], default='pull', max_length=4, null=True, verbose_name='Force'),
        ),
        migrations.AlterField(
            model_name='customuserexercise',
            name='mechanic',
            field=models.CharField(choices=[('comp', 'compound'), ('isol', 'isolation')], default='comp', max_length=4, null=True, verbose_name='Mechanic'),
        ),
        migrations.AlterField(
            model_name='customuserexercise',
            name='primary_muscles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('abs', 'abdominals'), ('ham', 'hamstrings'), ('cal', 'calves'), ('sho', 'shoulders'), ('add', 'adductors'), ('glu', 'glutes'), ('qua', 'quadriceps'), ('bic', 'biceps'), ('for', 'forearms'), ('abd', 'abductors'), ('tri', 'triceps'), ('che', 'chest'), ('mbk', 'middle back'), ('lbk', 'lower back'), ('tra', 'traps'), ('lat', 'lats'), ('nec', 'neck')], default='sho', max_length=100, null=True, verbose_name='Primary Muscles'),
        ),
        migrations.AlterField(
            model_name='customuserexercise',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Workout_Logbook.prefilledexercise'),
        ),
        migrations.AlterField(
            model_name='customuserexercise',
            name='secondary_muscles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('abs', 'abdominals'), ('ham', 'hamstrings'), ('cal', 'calves'), ('sho', 'shoulders'), ('add', 'adductors'), ('glu', 'glutes'), ('qua', 'quadriceps'), ('bic', 'biceps'), ('for', 'forearms'), ('abd', 'abductors'), ('tri', 'triceps'), ('che', 'chest'), ('mbk', 'middle back'), ('lbk', 'lower back'), ('tra', 'traps'), ('lat', 'lats'), ('nec', 'neck')], default='sho', max_length=100, null=True, verbose_name='Secondary Muscles'),
        ),
        migrations.AlterField(
            model_name='prefilledexercise',
            name='equipment',
            field=models.CharField(choices=[('bod', 'body only'), ('mac', 'machine'), ('ket', 'kettlebells'), ('dum', 'dumbbell'), ('cab', 'cable'), ('bar', 'barbell'), ('ban', 'bands'), ('med', 'medicine ball'), ('exe', 'exercise ball'), ('cba', 'e-z curl bar'), ('fro', 'foam roll')], default='mac', max_length=3, null=True, verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='prefilledexercise',
            name='force',
            field=models.CharField(choices=[('pull', 'Pull'), ('push', 'Push'), ('stat', 'Static')], default='pull', max_length=4, null=True, verbose_name='Force'),
        ),
        migrations.AlterField(
            model_name='prefilledexercise',
            name='mechanic',
            field=models.CharField(choices=[('comp', 'compound'), ('isol', 'isolation')], default='comp', max_length=4, null=True, verbose_name='Mechanic'),
        ),
        migrations.AlterField(
            model_name='prefilledexercise',
            name='primary_muscles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('abs', 'abdominals'), ('ham', 'hamstrings'), ('cal', 'calves'), ('sho', 'shoulders'), ('add', 'adductors'), ('glu', 'glutes'), ('qua', 'quadriceps'), ('bic', 'biceps'), ('for', 'forearms'), ('abd', 'abductors'), ('tri', 'triceps'), ('che', 'chest'), ('mbk', 'middle back'), ('lbk', 'lower back'), ('tra', 'traps'), ('lat', 'lats'), ('nec', 'neck')], default='sho', max_length=100, null=True, verbose_name='Primary Muscles'),
        ),
        migrations.AlterField(
            model_name='prefilledexercise',
            name='secondary_muscles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('abs', 'abdominals'), ('ham', 'hamstrings'), ('cal', 'calves'), ('sho', 'shoulders'), ('add', 'adductors'), ('glu', 'glutes'), ('qua', 'quadriceps'), ('bic', 'biceps'), ('for', 'forearms'), ('abd', 'abductors'), ('tri', 'triceps'), ('che', 'chest'), ('mbk', 'middle back'), ('lbk', 'lower back'), ('tra', 'traps'), ('lat', 'lats'), ('nec', 'neck')], default='sho', max_length=100, null=True, verbose_name='Secondary Muscles'),
        ),
    ]
