# Generated by Django 4.2.2 on 2023-06-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workout_Logbook', '0004_populate_prefilledexercise_table_based_on_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Workout_Logbook.workouttemplate', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='customuserexercise',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Exercise Name'),
        ),
        migrations.AlterField(
            model_name='prefilledexercise',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Exercise Name'),
        ),
        migrations.AlterField(
            model_name='settemplate',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout_Logbook.workoutexercisetemplate', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='workoutexercisetemplate',
            name='workout_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout_Logbook.workouttemplate', verbose_name='Workout'),
        ),
    ]
