# Generated by Django 4.2.2 on 2023-06-18 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workout_Logbook', '0005_workoutsession_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settemplate',
            name='rest_time',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Rest Time (sec)'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Workout_Logbook.customuserexercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='workoutexercisetemplate',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Workout_Logbook.customuserexercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Workout_Logbook.workouttemplate', verbose_name='Template'),
        ),
    ]
