# Generated by Django 4.2.2 on 2023-07-02 20:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout_Logbook', '0006_settemplate_rest_time_alter_workoutexercise_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphisyquestatus',
            name='body_fat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Body Fat (%)'),
        ),
    ]
